apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api
  namespace: nagp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: employee-api
  template:
    metadata:
      labels:
        app: employee-api
    spec:
      containers:
        - name: employee-api
          image: gauravjoshi03/employee-api:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: employee-api-config
                  key: PORT

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: employee-api-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: employee-api-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: employee-api-config
                  key: DB_NAME

            - name: DB_USER
              value: root

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
